// status
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'

export const TOGGLE_AUTHORIZE_VISIBLE = 'TOGGLE_AUTHORIZE_VISIBLE'

export const TOGGLE_POST_EDITOR_VISIBLE = 'TOGGLE_POST_EDITOR_VISIBLE'

export const TOGGLE_REPORT_EDITOR_VISIBLE = 'TOGGLE_REPORT_EDITOR_VISIBLE'

// user
export const CHANGE_USERNAME_TEXT = 'CHANGE_USERNAME_TEXT'

export const CHANGE_PASSWORD_TEXT = 'CHANGE_PASSWORD_TEXT'

export const CHANGE_EMAIL_TEXT = 'CHANGE_EMAIL_TEXT'

// post
export const INIT_POST = 'INIT_POST'

export const GET_POSTS_FETCH_SUCCESS = 'GET_POSTS_FETCH_SUCCESS'

export const CHANGE_POST_CONTENT = 'CHANGE_POST_CONTENT'

export const ENTER_POST_FETCH_SUCCESS = 'ENTER_POST_FETCH_SUCCESS'

export const DELETE_POST_FETCH_SUCCESS = 'DELETE_POST_FETCH_SUCCESS'

export const TOGGLE_POST_DETAIL_VISIBLE = 'TOGGLE_POST_DETAIL_VISIBLE'

export const CHANGE_POST_DETAIL = 'CHANGE_POST_DETAIL'

export const CHANGE_COMMENT_TEXT = 'CHANGE_COMMENT_TEXT'

export const ENTER_COMMENT_FETCH_SUCCESS = 'ENTER_COMMENT_FETCH_SUCCESS'

export const DELETE_COMMENT_FETCH_SUCCESS = 'DELETE_COMMENT_FETCH_SUCCESS'

// report
export const INIT_REPORT = 'INIT_REPORT'

export const GET_REPORTS_FETCH_SUCCESS = 'GET_REPORTS_FETCH_SUCCESS'

export const READY_REPORT = 'READY_REPORT'

export const CHANGE_REPORT_TYPE = 'CHANGE_REPORT_TYPE'

export const CHANGE_REPORT_DESCRIPTION = 'CHANGE_REPORT_DESCRIPTION'

export const ENTER_REPORT_FETCH_SUCCESS = 'ENTER_REPORT_FETCH_SUCCESS'

export const INVOKE_REPORT_FETCH_SUCCESS = 'INVOKE_REPORT_FETCH_SUCCESS'

export const REVOKE_REPORT_FETCH_SUCCESS = 'REVOKE_REPORT_FETCH_SUCCESS'
