export const CHANGE_POST_CONTENT = 'CHANGE_POST_CONTENT'

export const CHANGE_COMMENT_TEXT = 'CHANGE_COMMENT_TEXT'

export const CHANGE_USERNAME_TEXT = 'CHANGE_USERNAME_TEXT'

export const CHANGE_PASSWORD_TEXT = 'CHANGE_PASSWORD_TEXT'

export const CHANGE_EMAIL_TEXT = 'CHANGE_EMAIL_TEXT'

export const TOGGLE_AUTHORIZE_VISIBLE = 'TOGGLE_AUTHORIZE_VISIBLE'

export const TOGGLE_EDITOR_VISIBLE = 'TOGGLE_EDITOR_VISIBLE'

export const GET_POSTS = 'GET_POSTS'

export const CHANGE_CATEGORY = 'CHANGE_CATEGORY'

export const ENTER_POST_FETCH_SUCCESS = 'ENTER_POST_FETCH_SUCCESS'

export const ENTER_COMMENT_FETCH_SUCCESS = 'ENTER_COMMENT_FETCH_SUCCESS'

export const DELETE_POST_FETCH_SUCCESS = 'DELETE_POST_FETCH_SUCCESS'

export const DELETE_COMMENT_FETCH_SUCCESS = 'DELETE_COMMENT_FETCH_SUCCESS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
